import os

from django.conf import settings
from django.utils.translation import get_language

from mountains.models import Mountain


TEXT = {
    "ru": {
        "prepare_place_title": "Найдите место для похода",
        "prepare_place_placeholder": "Введите место для похода...",
        "prepare_place_find": "Найти",
        "prepare_place_min": "Введите не менее 3 символов, чтобы начать поиск.",
        "prepare_place_loading": "Ищем места…",
        "prepare_place_description": "Информация о месте",
        "prepare_place_location": "Расположение",
        "prepare_place_type": "Тип места",
        "prepare_place_trails": "Тропы поблизости",
        "prepare_place_no_trails": "Размеченные тропы поблизости не найдены.",
        "prepare_place_source": "Данные OpenStreetMap",
        "global_peak_index": "ВСЕМИРНЫЙ УКАЗАТЕЛЬ ВЕРШИН · ОТКРЫТЫЕ ДАННЫЕ",
        "nav_home": "Главная", "nav_mountains": "Горы", "nav_prepare": "Подготовка",
        "nav_weather": "Погода", "nav_stories": "Истории", "nav_assistant": "AI-помощник",
        "nav_profile": "Мой профиль", "nav_login": "Войти", "nav_signup": "Регистрация",
        "nav_logout": "Выйти", "hero_eyebrow": "АЛМАТЫ · КАЗАХСТАН",
        "hero_title": "Горы начинаются\nс подготовки.",
        "hero_subtitle": "Маршруты, погода и опыт сообщества — всё, чтобы ваш следующий выход в горы стал любимой историей.",
        "hero_primary": "Найти маршрут", "hero_secondary": "Как это работает",
        "hero_scroll": "Исследовать ниже", "home_mountains": "Маршруты, которые зовут",
        "home_mountains_sub": "От лёгких прогулок до вершин над облаками.", "view_all": "Все маршруты",
        "home_stories": "Следы, которые мы оставляем", "home_stories_sub": "Живые истории людей, для которых горы стали ближе.",
        "home_cta": "Ваш следующий рассвет выше облаков.", "home_cta_sub": "Выберите маршрут. Мы поможем подготовиться.",
        "explore_mountains": "Исследовать маршруты", "altitude": "Высота", "duration": "В пути",
        "difficulty": "Сложность", "easy": "Лёгкий", "moderate": "Средний", "hard": "Сложный",
        "mountains_title": "Маршруты рядом с небом", "mountains_sub": "Проверенные направления в горах Заилийского Алатау.",
        "details": "О маршруте", "prepare_trip": "Подготовиться к походу", "back_mountains": "Все маршруты",
        "route_facts": "Характеристики маршрута", "distance": "Расстояние", "best_season": "Сезон",
        "about_route": "О маршруте", "safety": "Безопасность прежде всего",
        "prepare_title": "Подготовьтесь с умом", "prepare_sub": "Соберите план, проверьте снаряжение и отправляйтесь уверенно.",
        "trip_plan": "План похода", "choose_mountain": "Маршрут", "season": "Сезон", "people": "Участники",
        "spring": "Весна", "summer": "Лето", "autumn": "Осень", "winter": "Зима",
        "gear_title": "Снаряжение", "gear_sub": "Отметьте то, что уже есть. Список сохранится в вашем профиле.",
        "have_it": "Есть", "need_it": "Нужно", "save_checklist": "Сохранить список",
        "stories_title": "Истории путешествий", "stories_sub": "Маршруты, открытия и советы от тех, кто уже вернулся.",
        "share_story": "Поделиться историей", "read_story": "Читать историю", "comments": "Комментарии",
        "write_comment": "Оставить комментарий", "send_comment": "Опубликовать", "tip": "Совет путешественникам",
        "equipment_used": "Снаряжение в походе", "author": "Автор", "published": "Опубликовано",
        "weather_title": "Погода в горах", "weather_sub": "Погода меняется быстро. Проверьте условия перед выходом.",
        "feels_like": "Ощущается как", "wind": "Ветер", "humidity": "Влажность", "precipitation": "Осадки",
        "visibility": "Видимость", "sunrise": "Рассвет", "sunset": "Закат", "forecast": "Прогноз",
        "today": "Сегодня", "tomorrow": "Завтра", "next_day": "Послезавтра", "weather_cloud": "Переменная облачность",
        "weather_rain": "Небольшой дождь", "weather_clear": "Ясно", "weather_source": "Демо-прогноз для Алматы",
        "assistant_title": "Ваш помощник в горах", "assistant_sub": "Расскажите о маршруте и снаряжении — подскажем, что взять.",
        "assistant_intro": "С чего начнём? Напишите, куда собираетесь и что уже положили в рюкзак.",
        "assistant_placeholder": "Например: иду на Фурмановку завтра, есть ботинки и 2 литра воды…",
        "assistant_send": "Отправить", "assistant_hint": "Советы помощника не заменяют прогноз и рекомендации спасателей.",
        "login_title": "С возвращением", "signup_title": "Начните своё путешествие",
        "username": "Имя пользователя", "password": "Пароль", "password_again": "Пароль ещё раз",
        "email": "Электронная почта", "login_submit": "Войти", "signup_submit": "Создать аккаунт",
        "no_account": "Впервые здесь?", "has_account": "Уже есть аккаунт?", "profile_title": "Ваш профиль",
        "edit_profile": "Редактировать профиль", "save_changes": "Сохранить изменения", "my_stories": "Мои истории",
        "saved_routes": "Сохранённые маршруты", "no_stories": "Пока нет историй. Ваш первый поход может стать началом.",
        "story_create_title": "Расскажите свою историю", "story_title": "Заголовок", "story_mountain": "Гора",
        "story_date": "Дата похода", "story_difficulty": "Сложность", "story_description": "История похода",
        "story_tips": "Полезные советы", "story_equipment": "Что взяли с собой", "story_cover": "Фото обложки",
        "publish_story": "Опубликовать историю", "footer_note": "Ближе к горам. Готовы к пути.",
        "footer_explore": "Исследовать", "footer_community": "Сообщество", "footer_rights": "Все права защищены.",
        "search_placeholder": "Найдите свою вершину", "search_button": "Найти", "no_results": "Пока маршрутов нет.",
        "name": "Название", "duration_hours": "Часов в пути", "people_count": "Количество человек",
        "equipment_category_clothing": "Одежда", "equipment_category_navigation": "Навигация",
        "equipment_category_food": "Еда и вода", "equipment_category_safety": "Безопасность",
        "equipment_category_camping": "Ночёвка", "assistant_error": "Не удалось получить ответ. Попробуйте ещё раз.",
        "weather_loading": "Проверяем погоду…", "profile_bio": "О себе", "profile_region": "Город",
        "profile_avatar": "Ссылка на фото", "like": "Нравится", "liked": "В избранном",
    },
    "kk": {
        "prepare_place_title": "Жорыққа арналған орынды іздеу",
        "prepare_place_placeholder": "Жорық орнын енгізіңіз...",
        "prepare_place_find": "Іздеу",
        "prepare_place_min": "Іздеу үшін кемінде 3 таңба енгізіңіз.",
        "prepare_place_loading": "Орындар ізделуде…",
        "prepare_place_description": "Орын туралы ақпарат",
        "prepare_place_location": "Орналасуы",
        "prepare_place_type": "Орын түрі",
        "prepare_place_trails": "Жақын маңдағы соқпақтар",
        "prepare_place_no_trails": "Жақын маңнан белгіленген соқпақтар табылмады.",
        "prepare_place_source": "OpenStreetMap деректері",
        "global_peak_index": "ӘЛЕМ ШЫҢДАРЫНЫҢ ТІЗІМІ · АШЫҚ ДЕРЕК",
        "nav_home": "Басты бет", "nav_mountains": "Таулар", "nav_prepare": "Дайындық",
        "nav_weather": "Ауа райы", "nav_stories": "Хикаялар", "nav_assistant": "AI көмекші",
        "nav_profile": "Профиль", "nav_login": "Кіру", "nav_signup": "Тіркелу", "nav_logout": "Шығу",
        "hero_eyebrow": "АЛМАТЫ · ҚАЗАҚСТАН", "hero_title": "Тауларға жол\nдайындықтан басталады.",
        "hero_subtitle": "Бағыттар, ауа райы және саяхатшылар тәжірибесі — келесі сапарыңыз ұмытылмас болсын.",
        "hero_primary": "Бағыт таңдау", "hero_secondary": "Қалай жұмыс істейді", "hero_scroll": "Төменге өту",
        "home_mountains": "Шақыратын бағыттар", "home_mountains_sub": "Жеңіл серуеннен бұлттан биік шыңдарға дейін.",
        "view_all": "Барлық бағыттар", "home_stories": "Жолда қалған іздер", "home_stories_sub": "Тауларды жақын сезінген жандардың шынайы хикаялары.",
        "home_cta": "Бұлттан биік келесі таң сізді күтеді.", "home_cta_sub": "Бағытты таңдаңыз. Дайындыққа көмектесеміз.",
        "explore_mountains": "Бағыттарды көру", "altitude": "Биіктік", "duration": "Жол уақыты", "difficulty": "Қиындық",
        "easy": "Жеңіл", "moderate": "Орташа", "hard": "Қиын", "mountains_title": "Аспанға жақын бағыттар",
        "mountains_sub": "Іле Алатауындағы тексерілген бағыттар.", "details": "Бағыт туралы", "prepare_trip": "Жорыққа дайындалу",
        "back_mountains": "Барлық бағыттар", "route_facts": "Бағыт сипаттамасы", "distance": "Қашықтық", "best_season": "Маусым",
        "about_route": "Бағыт туралы", "safety": "Қауіпсіздік маңызды", "prepare_title": "Ақылды дайындалыңыз",
        "prepare_sub": "Жоспар құрыңыз, жабдықты тексеріңіз, сенімді жолға шығыңыз.", "trip_plan": "Жорық жоспары",
        "choose_mountain": "Бағыт", "season": "Маусым", "people": "Қатысушылар", "spring": "Көктем", "summer": "Жаз",
        "autumn": "Күз", "winter": "Қыс", "gear_title": "Жабдықтар", "gear_sub": "Бар заттарды белгілеңіз. Тізім профильде сақталады.",
        "have_it": "Бар", "need_it": "Керек", "save_checklist": "Тізімді сақтау", "stories_title": "Саяхат хикаялары",
        "stories_sub": "Қайтып келген саяхатшылардың бағыттары мен кеңестері.", "share_story": "Хикаямен бөлісу",
        "read_story": "Хикаяны оқу", "comments": "Пікірлер", "write_comment": "Пікір қалдыру", "send_comment": "Жариялау",
        "tip": "Саяхатшыларға кеңес", "equipment_used": "Жабдықтар", "author": "Автор", "published": "Жарияланды",
        "weather_title": "Таудағы ауа райы", "weather_sub": "Тауда ауа райы тез өзгереді. Жолға шықпас бұрын тексеріңіз.",
        "feels_like": "Сезіледі", "wind": "Жел", "humidity": "Ылғалдылық", "precipitation": "Жауын-шашын",
        "visibility": "Көріну", "sunrise": "Күн шығуы", "sunset": "Күн батуы", "forecast": "Болжам", "today": "Бүгін",
        "tomorrow": "Ертең", "next_day": "Бүрсігүні", "weather_cloud": "Ала бұлтты", "weather_rain": "Аздаған жаңбыр", "weather_clear": "Ашық",
        "weather_source": "Алматыға арналған демо болжам", "assistant_title": "Таудағы көмекшіңіз",
        "assistant_sub": "Бағыт пен жабдық туралы жазыңыз — не алу керегін айтамыз.",
        "assistant_intro": "Қайдан бастаймыз? Қайда баратыныңызды және сөмкеге не салғаныңызды жазыңыз.",
        "assistant_placeholder": "Мысалы: ертең Фурмановкаға барамын, етігім мен 2 литр суым бар…",
        "assistant_send": "Жіберу", "assistant_hint": "Көмекші кеңесі ауа райы болжамы мен құтқарушылар кеңесін алмастырмайды.",
        "login_title": "Қайта қош келдіңіз", "signup_title": "Саяхатыңызды бастаңыз", "username": "Пайдаланушы аты",
        "password": "Құпиясөз", "password_again": "Құпиясөзді қайталаңыз", "email": "Электрондық пошта",
        "login_submit": "Кіру", "signup_submit": "Тіркелгі ашу", "no_account": "Жаңа келдіңіз бе?", "has_account": "Тіркелгіңіз бар ма?",
        "profile_title": "Профиліңіз", "edit_profile": "Профильді өңдеу", "save_changes": "Өзгерістерді сақтау",
        "my_stories": "Менің хикаяларым", "saved_routes": "Сақталған бағыттар", "no_stories": "Әзірше хикая жоқ. Алғашқы жорығыңыздан бастаңыз.",
        "story_create_title": "Хикаяңызды бөлісіңіз", "story_title": "Тақырып", "story_mountain": "Тау", "story_date": "Жорық күні",
        "story_difficulty": "Қиындық", "story_description": "Жорық хикаясы", "story_tips": "Пайдалы кеңестер",
        "story_equipment": "Алған жабдықтар", "story_cover": "Мұқаба суреті", "publish_story": "Хикаяны жариялау",
        "footer_note": "Тауларға жақын. Жолға дайын.", "footer_explore": "Зерттеу", "footer_community": "Қауымдастық",
        "footer_rights": "Барлық құқықтар қорғалған.", "search_placeholder": "Өз шыңыңызды табыңыз", "search_button": "Іздеу",
        "no_results": "Әзірше бағыт жоқ.", "name": "Атауы", "duration_hours": "Жол сағаты", "people_count": "Адам саны",
        "equipment_category_clothing": "Киім", "equipment_category_navigation": "Бағдарлау", "equipment_category_food": "Тамақ пен су",
        "equipment_category_safety": "Қауіпсіздік", "equipment_category_camping": "Қону", "assistant_error": "Жауап алынбады. Қайталап көріңіз.",
        "weather_loading": "Ауа райы тексерілуде…", "profile_bio": "Өзім туралы", "profile_region": "Қала", "profile_avatar": "Фото сілтемесі",
        "like": "Ұнату", "liked": "Таңдаулыда",
    },
    "en": {
        "prepare_place_title": "Find a hiking place",
        "prepare_place_placeholder": "Enter a place for your hike...",
        "prepare_place_find": "Find",
        "prepare_place_min": "Enter at least 3 characters to search.",
        "prepare_place_loading": "Searching places…",
        "prepare_place_description": "About this place",
        "prepare_place_location": "Location",
        "prepare_place_type": "Place type",
        "prepare_place_trails": "Nearby trails",
        "prepare_place_no_trails": "No mapped trails found nearby.",
        "prepare_place_source": "OpenStreetMap data",
        "global_peak_index": "GLOBAL PEAK INDEX · OPEN DATA",
        "nav_home": "Home", "nav_mountains": "Mountains", "nav_prepare": "Prepare", "nav_weather": "Weather",
        "nav_stories": "Stories", "nav_assistant": "AI guide", "nav_profile": "My profile", "nav_login": "Sign in",
        "nav_signup": "Join", "nav_logout": "Sign out", "hero_eyebrow": "ALMATY · KAZAKHSTAN",
        "hero_title": "Every great summit\nstarts with a plan.",
        "hero_subtitle": "Routes, mountain weather and real community knowledge for a better day above the city.",
        "hero_primary": "Explore routes", "hero_secondary": "How it works", "hero_scroll": "Discover below",
        "home_mountains": "Routes worth waking up for", "home_mountains_sub": "From easy walks to summits above the clouds.",
        "view_all": "All routes", "home_stories": "Stories from the trail", "home_stories_sub": "Real days outside, shared by people who know these mountains.",
        "home_cta": "Your next sunrise is above the clouds.", "home_cta_sub": "Pick a route. We’ll help you get ready.",
        "explore_mountains": "Explore routes", "altitude": "Elevation", "duration": "On trail", "difficulty": "Difficulty",
        "easy": "Easy", "moderate": "Moderate", "hard": "Challenging", "mountains_title": "Closer to the sky",
        "mountains_sub": "Handpicked routes across the Ile Alatau range.", "details": "Route details", "prepare_trip": "Plan this hike",
        "back_mountains": "All routes", "route_facts": "At a glance", "distance": "Distance", "best_season": "Best season",
        "about_route": "About the route", "safety": "A note on safety", "prepare_title": "Make a good plan",
        "prepare_sub": "Set your route, check your kit and head out with confidence.", "trip_plan": "Your trip",
        "choose_mountain": "Route", "season": "Season", "people": "Group size", "spring": "Spring", "summer": "Summer",
        "autumn": "Autumn", "winter": "Winter", "gear_title": "Your kit", "gear_sub": "Tick what you own. Your checklist stays in your profile.",
        "have_it": "Packed", "need_it": "Need it", "save_checklist": "Save checklist", "stories_title": "Trail stories",
        "stories_sub": "Routes, discoveries and useful advice from hikers who made it back.", "share_story": "Share a story",
        "read_story": "Read story", "comments": "Comments", "write_comment": "Leave a comment", "send_comment": "Post comment",
        "tip": "Trail tip", "equipment_used": "Kit used", "author": "By", "published": "Published",
        "weather_title": "Mountain weather", "weather_sub": "Conditions change fast up high. Check before you set out.",
        "feels_like": "Feels like", "wind": "Wind", "humidity": "Humidity", "precipitation": "Precipitation",
        "visibility": "Visibility", "sunrise": "Sunrise", "sunset": "Sunset", "forecast": "Forecast", "today": "Today",
        "tomorrow": "Tomorrow", "next_day": "Next day", "weather_cloud": "Partly cloudy", "weather_rain": "Light rain", "weather_clear": "Clear",
        "weather_source": "Sample forecast for Almaty", "assistant_title": "Your mountain guide", "assistant_sub": "Tell us about your route and kit. We’ll help you spot what’s missing.",
        "assistant_intro": "Where are you headed? Tell me about the route and what’s already in your pack.",
        "assistant_placeholder": "For example: Furmanovka tomorrow, boots and two litres of water…", "assistant_send": "Send",
        "assistant_hint": "Guide suggestions do not replace forecasts or advice from local rescue services.",
        "login_title": "Welcome back", "signup_title": "Start your next adventure", "username": "Username", "password": "Password",
        "password_again": "Confirm password", "email": "Email address", "login_submit": "Sign in", "signup_submit": "Create account",
        "no_account": "New to the trail?", "has_account": "Already have an account?", "profile_title": "Your profile",
        "edit_profile": "Edit profile", "save_changes": "Save changes", "my_stories": "My stories", "saved_routes": "Saved routes",
        "no_stories": "No stories yet. Your first day out could be the start of one.", "story_create_title": "Tell your trail story",
        "story_title": "Title", "story_mountain": "Mountain", "story_date": "Hike date", "story_difficulty": "Difficulty",
        "story_description": "Your story", "story_tips": "Useful tips", "story_equipment": "Kit you used", "story_cover": "Cover photo",
        "publish_story": "Publish story", "footer_note": "Closer to the mountains. Ready for the way.", "footer_explore": "Explore",
        "footer_community": "Community", "footer_rights": "All rights reserved.", "search_placeholder": "Find your next summit",
        "search_button": "Search", "no_results": "No routes found yet.", "name": "Name", "duration_hours": "Hours on trail",
        "people_count": "Group size", "equipment_category_clothing": "Clothing", "equipment_category_navigation": "Navigation",
        "equipment_category_food": "Food & water", "equipment_category_safety": "Safety", "equipment_category_camping": "Overnight",
        "assistant_error": "Could not get a reply. Please try again.", "weather_loading": "Checking conditions…", "profile_bio": "About you",
        "profile_region": "Home town", "profile_avatar": "Photo URL", "like": "Like", "liked": "Saved",
    },
}

EXTRA_TEXT = {
    "ru": {
        "world_search_title": "\u041c\u0435\u0441\u0442\u0430 \u0438 \u0432\u0435\u0440\u0448\u0438\u043d\u044b \u043d\u0430 \u043a\u0430\u0440\u0442\u0435",
        "world_search_sub": "\u041d\u0430\u0439\u0434\u0438\u0442\u0435 \u0432\u0435\u0440\u0448\u0438\u043d\u0443, \u0433\u043e\u0440\u043e\u0434 \u0438\u043b\u0438 \u043c\u0435\u0441\u0442\u043e, \u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 \u041c\u0435\u0434\u0435\u0443. \u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442, \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c \u043a\u0430\u0440\u0442\u0443, \u043f\u043e\u0433\u043e\u0434\u0443 \u0438 \u0431\u043b\u0438\u0436\u0430\u0439\u0448\u0438\u0435 \u0442\u0440\u043e\u043f\u044b.",
        "world_search_placeholder": "\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, \u041c\u0435\u0434\u0435\u0443, \u0410\u043b\u043c\u0430\u0442\u044b \u0438\u043b\u0438 Fuji",
        "world_search_submit": "Искать",
        "world_search_min": "Введите не менее 3 символов.",
        "world_search_loading": "Ищем вершины…",
        "world_search_none": "\u041c\u0435\u0441\u0442\u043e \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u043e. \u041f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0434\u0440\u0443\u0433\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435.",
        "world_search_error": "Поиск временно недоступен. Попробуйте позже.",
        "world_search_rate": "Поиск занят. Подождите секунду и попробуйте ещё раз.",
        "world_search_source": "Результаты OpenStreetMap",
        "map_title": "Карта маршрута",
        "map_prompt": "Найдите вершину, чтобы загрузить местоположение и нанесённые тропы.",
        "map_loading": "Загружаем тропы OpenStreetMap…",
        "map_none": "Рядом нет размеченных пеших маршрутов. Показана только вершина; тропа не подтверждена.",
        "map_error": "Данные троп временно недоступны. Местоположение вершины показано на карте.",
        "map_rate": "Сервис карты занят. Попробуйте запросить тропы через несколько секунд.",
        "map_start": "Начало тропы OpenStreetMap",
        "map_finish": "Конец тропы OpenStreetMap",
        "map_trail_segment": "Нанесённая тропа OpenStreetMap",
        "map_peak": "Вершина",
        "map_coordinates": "Координаты",
        "map_elevation_missing": "Высота не указана в источнике",
        "map_safety_note": "Тропы OpenStreetMap могут быть неполными и не заменяют официальную карту или местные рекомендации.",
        "map_no_library": "Карта не загрузилась. Проверьте подключение к картографическому сервису.",
        "weather_api_key_missing": "Для актуальной погоды добавьте WEATHER_API_KEY в файл .env.",
        "weather_api_error": "Не удалось загрузить погоду для этих координат. Попробуйте позже.",
        "weather_coordinates_error": "Для этой вершины нет корректных координат погоды.",
        "weather_forecast_error": "Текущая погода доступна, но прогноз временно не загрузился.",
        "weather_hourly": "Почасовой прогноз",
        "weather_daily": "На 5 дней",
        "weather_precipitation_probability": "Вероятность осадков",
        "weather_place": "Место",
        "assistant_open": "Открыть AI-помощника",
        "assistant_close": "Закрыть AI-помощника",
        "assistant_dock_title": "Помощник в горах",
        "assistant_demo_mode": "Локальный режим",
        "assistant_live_mode": "AI подключён",
    },
    "kk": {
        "world_search_title": "\u041e\u0440\u044b\u043d\u0434\u0430\u0440 \u043c\u0435\u043d \u0448\u044b\u04a3\u0434\u0430\u0440\u0434\u044b \u043a\u0430\u0440\u0442\u0430\u0434\u0430\u043d \u0456\u0437\u0434\u0435\u0443",
        "world_search_sub": "\u041c\u0435\u0434\u0435\u0443 \u0441\u0438\u044f\u049b\u0442\u044b \u0448\u044b\u04a3\u0434\u044b, \u049b\u0430\u043b\u0430\u043d\u044b \u043d\u0435\u043c\u0435\u0441\u0435 \u043e\u0440\u044b\u043d\u0434\u044b \u0442\u0430\u0431\u044b\u043f, \u043a\u0430\u0440\u0442\u0430\u043d\u044b, \u0430\u0443\u0430 \u0440\u0430\u0439\u044b\u043d \u0436\u04d9\u043d\u0435 \u0436\u0430\u049b\u044b\u043d \u0441\u043e\u049b\u043f\u0430\u049b\u0442\u0430\u0440\u0434\u044b \u043a\u04e9\u0440\u0456\u04a3\u0456\u0437.",
        "world_search_placeholder": "\u041c\u044b\u0441\u0430\u043b\u044b, \u041c\u0435\u0434\u0435\u0443, \u0410\u043b\u043c\u0430\u0442\u044b \u043d\u0435\u043c\u0435\u0441\u0435 Fuji",
        "world_search_submit": "Іздеу",
        "world_search_min": "Кемінде 3 таңба енгізіңіз.",
        "world_search_loading": "Шыңдар ізделуде…",
        "world_search_none": "\u041e\u0440\u044b\u043d \u0442\u0430\u0431\u044b\u043b\u043c\u0430\u0434\u044b. \u0411\u0430\u0441\u049b\u0430 \u0430\u0442\u0430\u0443\u043c\u0435\u043d \u0456\u0437\u0434\u0435\u043f \u043a\u04e9\u0440\u0456\u04a3\u0456\u0437.",
        "world_search_error": "Іздеу уақытша қолжетімсіз. Кейін қайталап көріңіз.",
        "world_search_rate": "Іздеу бос емес. Бір секунд күтіп, қайта көріңіз.",
        "world_search_source": "OpenStreetMap нәтижелері",
        "map_title": "Жорық картасы",
        "map_prompt": "Орны мен картадағы соқпақтарды көру үшін шыңды іздеңіз.",
        "map_loading": "OpenStreetMap соқпақтары жүктелуде…",
        "map_none": "Жақын маңда белгіленген жаяу бағыт жоқ. Тек шың көрсетілді; соқпақ расталмаған.",
        "map_error": "Соқпақ деректері уақытша қолжетімсіз. Шың орны картада көрсетілді.",
        "map_rate": "Карта қызметі бос емес. Бірнеше секундтан соң қайталап көріңіз.",
        "map_start": "OpenStreetMap соқпағының басы",
        "map_finish": "OpenStreetMap соқпағының соңы",
        "map_trail_segment": "OpenStreetMap-та белгіленген соқпақ",
        "map_peak": "Шың",
        "map_coordinates": "Координаттар",
        "map_elevation_missing": "Дереккөзде биіктік көрсетілмеген",
        "map_safety_note": "OpenStreetMap соқпақтары толық болмауы мүмкін; ресми картаны немесе жергілікті кеңесті алмастырмайды.",
        "map_no_library": "Карта жүктелмеді. Карта қызметіне қосылымды тексеріңіз.",
        "weather_api_key_missing": "Ағымдағы ауа райы үшін .env файлына WEATHER_API_KEY қосыңыз.",
        "weather_api_error": "Осы координаттарға ауа райын жүктеу мүмкін болмады. Кейін қайталап көріңіз.",
        "weather_coordinates_error": "Бұл шың үшін ауа райының жарамды координаттары жоқ.",
        "weather_forecast_error": "Ағымдағы ауа райы бар, бірақ болжам уақытша жүктелмеді.",
        "weather_hourly": "Сағаттық болжам",
        "weather_daily": "5 күнге",
        "weather_precipitation_probability": "Жауын-шашын ықтималдығы",
        "weather_place": "Орын",
        "assistant_open": "AI көмекшіні ашу",
        "assistant_close": "AI көмекшіні жабу",
        "assistant_dock_title": "Таудағы көмекші",
        "assistant_demo_mode": "Жергілікті режим",
        "assistant_live_mode": "AI қосылған",
    },
    "en": {
        "world_search_title": "Places and peaks on the map",
        "world_search_sub": "Find a peak, city, or place such as Medeu to view its map, local weather, and nearby trails.",
        "world_search_placeholder": "For example, Medeu, Almaty, or Fuji",
        "world_search_submit": "Search",
        "world_search_min": "Enter at least 3 characters.",
        "world_search_loading": "Searching peaks…",
        "world_search_none": "Place not found. Try another name.",
        "world_search_error": "Search is temporarily unavailable. Try again later.",
        "world_search_rate": "Search is busy. Wait a moment and try again.",
        "world_search_source": "OpenStreetMap results",
        "map_title": "Trail map",
        "map_prompt": "Search for a peak to load its location and mapped trails.",
        "map_loading": "Loading OpenStreetMap trails…",
        "map_none": "No mapped hiking relations were found nearby. The peak is shown; no trail is implied.",
        "map_error": "Trail data is temporarily unavailable. The peak location is still shown.",
        "map_rate": "The map service is busy. Try loading trails again in a few seconds.",
        "map_start": "OpenStreetMap trail start",
        "map_finish": "OpenStreetMap trail end",
        "map_trail_segment": "Mapped OpenStreetMap trail",
        "map_peak": "Peak",
        "map_coordinates": "Coordinates",
        "map_elevation_missing": "Elevation is not listed by the source",
        "map_safety_note": "OpenStreetMap trails may be incomplete and are not a substitute for official maps or local advice.",
        "map_no_library": "The map did not load. Check your connection to the mapping service.",
        "weather_api_key_missing": "Add WEATHER_API_KEY to .env to load live weather.",
        "weather_api_error": "Weather could not be loaded for these coordinates. Try again later.",
        "weather_coordinates_error": "No valid weather coordinates are available for this peak.",
        "weather_forecast_error": "Current conditions are available, but the forecast did not load.",
        "weather_hourly": "Hourly forecast",
        "weather_daily": "5-day forecast",
        "weather_precipitation_probability": "Chance of precipitation",
        "weather_place": "Location",
        "assistant_open": "Open AI hiking assistant",
        "assistant_close": "Close AI hiking assistant",
        "assistant_dock_title": "Mountain guide",
        "assistant_demo_mode": "Local mode",
        "assistant_live_mode": "AI connected",
    },
}


def interface_text(request):
    language = (get_language() or "ru").split("-")[0]
    is_admin = request.path.startswith("/admin/")
    return {
        "T": {**TEXT.get(language, TEXT["ru"]), **EXTRA_TEXT.get(language, EXTRA_TEXT["ru"])},
        "CURRENT_LANGUAGE": language,
        "LANGUAGES": [("ru", "Русский"), ("kk", "Қазақша"), ("en", "English")],
        "MAP_TILE_URL": settings.MAP_TILE_URL,
        "MAP_TILE_ATTRIBUTION": settings.MAP_TILE_ATTRIBUTION,
        "AI_CONFIGURED": bool(os.getenv("AI_API_KEY", "").strip()),
        "ASSISTANT_MOUNTAINS": () if is_admin else Mountain.objects.only("name", "latitude", "longitude"),
        "ASSISTANT_DIFFICULTY_CHOICES": Mountain.DIFFICULTY_CHOICES,
    }
